### ISSUE TITLE
feat-req(?): When starting a new quet, pop-out controls are closed

### ISSUE THREAD

**Issue by txj-xyz** [Techpure2013/RS3QuestBuddy#10]
- Popout closes when I finish a quest
- (unrelated) Quest details are not a default, a bit confusing to tell new users how to start seeing steps to progress with the Pop-out controls
- Coordinates of the Pop-out controls are also reset and not saved

**Comment by txj-xyz** [comment]
Looks good on 1080p screen though.

![image](https://github.com/Techpure2013/RS3QuestBuddy/assets/7461476/25181531-405a-455d-b843-ab7f49c67ddf)

**Comment by Techpure2013** [comment]
Every instance of a new quest is a new page so working as intended
