### ISSUE TITLE
UI not scrolling enough during quest

### ISSUE THREAD

**Issue by dovry** [Techpure2013/RS3QuestBuddy#15]
The UI doesn't scroll enough when completing task

There's no need to see the 3 previous tasks, and navigating by 'completing' the current task can be misleading.

If the UI is longer it's still showing the 3 last completed, and 1 to-do task

minimal ui, step 15 is the 'current' step
![image](https://github.com/Techpure2013/RS3QuestBuddy/assets/15201298/d9713d59-6c0b-4172-92f5-a44cd85c30c5)

large ui
![image](https://github.com/Techpure2013/RS3QuestBuddy/assets/15201298/19e3bbf8-5edb-4bbe-91dd-fecbf6c02439)

proposed solution: scroll further down when completing

**Comment by Techpure2013** [comment]
I'll look into this. Been swamped at work this week.
