### ISSUE TITLE
Icons instead of text in UI

### ISSUE THREAD

**Issue by dovry** [Techpure2013/RS3QuestBuddy#16]
![image](https://github.com/Techpure2013/RS3QuestBuddy/assets/15201298/0725833e-e201-4ba4-8d95-92d8768d8a97)

proposed:

- return to top = up arrow
- Images = 'images' icon
- Next/Previous = left/right arrow

**Comment by Techpure2013** [comment]
My only concern is  the vagueness. But I will think on this. Maybe put it as a setting.
