### ISSUE TITLE
bug: Quest steps displaying in wrong direction

### ISSUE THREAD

**Issue by ChristopherSterza** [Techpure2013/RS3QuestBuddy#25]
**Describe the bug**
When using RS3 Quest Buddy via alt1 and displaying a quest's steps, the steps are displayed horizontally instead of vertically. This started occurring to me after the pushes on 12/14.

![before](https://github.com/user-attachments/assets/c29ef9c3-aa2c-498c-a84f-6de5199f632e)

**Steps to reproduce:**
1. Open the RS3 Quest Buddy plugin
2. Select a quest
3. Click the "Show Quest Steps" button
4. View the quest steps

**Possible solution**
Check the css for the stepper component. I found that when I inspected the mantine-Stepper-steps and specified the flex direction to column and set align-items to stretch, the stepper more resembled what it looked like before the bug.

![changes](https://github.com/user-attachments/assets/69009f05-b8a0-4273-adda-5cfc15cd9f68)

**Comment by Techpure2013** [comment]
Whats crazy is I tried other means of css but it fixed itself when people updated from alt1 1.5.6 to 1.6 because of chromiums version also updating but ill add the code to the dist to see if it fixes as well.
